name: Pêche Port-Gentil
version: "1.0.3"
slug: peche
description: Journal de bord & suivi VMS pour la pêche artisanale (compatible NEMO)
url: https://github.com/KingjulianB/ha-addon-peche
arch:
  - aarch64
  - amd64
  - armv7
ports:
  3000/tcp: 3000
ports_description:
  3000/tcp: Interface web de l'application pêche
options:
  app_password: changez-moi
  nemo_api_url: ""
  nemo_api_key: ""
  nemo_device_id: ""
schema:
  app_password: str
  nemo_api_url: str?
  nemo_api_key: str?
  nemo_device_id: str?
hassio_api: false
homeassistant_api: false
init: false
